### PR TITLE
Only allow one replica of Citadel

### PR DESCRIPTION
**Pull request by lei-tang**
This PR is for the issue: https://github.com/istio/istio/issues/13383. The counterpart of this PR on istio/istio repo is at https://github.com/istio/istio/pull/13519.

### CODE REVIEW

**Comment by loewenstein** [comment]
@lei-tang can we make Citadel work with multiple replicas instead? With SDS Citadel gets on a more critical path, doesn't it? If a workload gets scheduled on a node the first time, the node agent needs the CSR done by Citadel in order to start serving traffic, right?

**Comment by lei-tang** [comment]
In SDS-Citadel flow, Citadel may in theory have multiple replicas to serve CSRs from Node Agents. But overall multi-replica Citadel is still under development; currently for secret-mount-based Citadel when multiple Citadel are deployed, they have race condition. Per the quote from @jcetkov in https://github.com/istio/istio/issues/13383: "it might be appropriate to modify the helm charts not to allow setting the security replica count via variable, if such case is really not supported and results in hard to trace issues."

**Pull request merged**
